# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Accueil.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(809, 607)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setSizeIncrement(QtCore.QSize(1000, 1000))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 801, 641))
        self.widget.setStyleSheet("border-radius:50px;\n"
"\n"
"background-color: rgb(27, 19, 57);\n"
"")
        self.widget.setObjectName("widget")
        self.leftWidget = QtWidgets.QWidget(self.widget)
        self.leftWidget.setGeometry(QtCore.QRect(10, 10, 221, 591))
        self.leftWidget.setStyleSheet("#leftWidget\n"
"\n"
"{\n"
"\n"
"    width:260px;\n"
"    background:#1F1F1F;\n"
"    background-color:  rgb(181, 120, 255);\n"
"}")
        self.leftWidget.setObjectName("leftWidget")
        self.label = QtWidgets.QLabel(self.leftWidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 181))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/GestionStock.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.leftWidget)
        self.label_2.setGeometry(QtCore.QRect(0, 200, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 15pt \"Snap ITC\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.addEmpButton = QtWidgets.QPushButton(self.leftWidget)
        self.addEmpButton.setGeometry(QtCore.QRect(0, 280, 211, 44))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addEmpButton.setFont(font)
        self.addEmpButton.setStyleSheet("#addEmpButton\n"
"{\n"
"    text-align:left;\n"
"    padding-left:26px;\n"
"    border:none;    \n"
"    color:white;    \n"
"    background:#1F1F1F;\n"
"    background-color: rgb(153, 85, 255);\n"
"    border-left:6px solid dodgerblue;\n"
"}\n"
"#addEmpButton:hover\n"
"{\n"
"    text-align:left;\n"
"    padding-left:26px;\n"
"    border:none;    \n"
"    color:white;    \n"
"    background:#333;\n"
"    \n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ic/icons8-ajouter-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addEmpButton.setIcon(icon)
        self.addEmpButton.setIconSize(QtCore.QSize(32, 32))
        self.addEmpButton.setObjectName("addEmpButton")
        self.updateEmpButton = QtWidgets.QPushButton(self.leftWidget)
        self.updateEmpButton.setGeometry(QtCore.QRect(0, 340, 211, 44))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.updateEmpButton.setFont(font)
        self.updateEmpButton.setStyleSheet("#updateEmpButton\n"
"{\n"
"    text-align:left;\n"
"    padding-left:26px;\n"
"    border-radius:50px;\n"
"    color:white;    \n"
"    background:#1F1F1F;\n"
"    background-color: rgb(153, 85, 255);\n"
"    border-left:6px solid dodgerblue;\n"
"}\n"
"#updateEmpButton:hover\n"
"{\n"
"    text-align:left;\n"
"    padding-left:26px;\n"
"    border:none;    \n"
"    color:white;    \n"
"    background:#333;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ic/UPDATE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateEmpButton.setIcon(icon1)
        self.updateEmpButton.setIconSize(QtCore.QSize(32, 32))
        self.updateEmpButton.setObjectName("updateEmpButton")
        self.deleteEmpButton = QtWidgets.QPushButton(self.leftWidget)
        self.deleteEmpButton.setGeometry(QtCore.QRect(130, 400, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.deleteEmpButton.setFont(font)
        self.deleteEmpButton.setStyleSheet("#deleteEmpButton\n"
"{\n"
"    text-align:left;\n"
"    padding-left:26px;\n"
"    border-radius:50px;\n"
"    color:white;    \n"
"    background:#1F1F1F;\n"
"    border-left:6px solid dodgerblue;\n"
"    background-color:  rgb(181, 120, 255);\n"
"}\n"
"#deleteEmpButton:hover\n"
"{\n"
"    text-align:left;\n"
"    padding-left:26px;\n"
"    border:none;    \n"
"    color:white;    \n"
"    background:#333;\n"
"}")
        self.deleteEmpButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ic/icons8-supprimer-la-corbeille-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteEmpButton.setIcon(icon2)
        self.deleteEmpButton.setIconSize(QtCore.QSize(61, 43))
        self.deleteEmpButton.setObjectName("deleteEmpButton")
        self.label_9 = QtWidgets.QLabel(self.leftWidget)
        self.label_9.setGeometry(QtCore.QRect(10, 540, 211, 31))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(181, 120, 255);")
        self.label_9.setObjectName("label_9")
        self.deletefield = QtWidgets.QLineEdit(self.leftWidget)
        self.deletefield.setGeometry(QtCore.QRect(0, 400, 131, 41))
        self.deletefield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(251, 130, 255);\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"")
        self.deletefield.setObjectName("deletefield")
        self.nbrr = QtWidgets.QPushButton(self.leftWidget)
        self.nbrr.setGeometry(QtCore.QRect(0, 470, 211, 51))
        self.nbrr.setStyleSheet("#nbrr\n"
"{\n"
"    text-align:left;\n"
"    padding-left:26px;\n"
"    border-radius:50px;\n"
"    color:white;    \n"
"    background:#1F1F1F;\n"
"    border-left:6px solid dodgerblue;\n"
"    background-color: rgb(153, 85, 255);\n"
"}\n"
"#nbrr:hover\n"
"{\n"
"    text-align:left;\n"
"    padding-left:26px;\n"
"    border:none;    \n"
"    color:white;    \n"
"    background:#333;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ic/icons8-compteur-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nbrr.setIcon(icon3)
        self.nbrr.setIconSize(QtCore.QSize(52, 58))
        self.nbrr.setObjectName("nbrr")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(740, 0, 75, 61))
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ic/icons8-sortie-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.searchfield = QtWidgets.QLineEdit(self.widget)
        self.searchfield.setGeometry(QtCore.QRect(250, 10, 221, 40))
        self.searchfield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(251, 130, 255);\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"")
        self.searchfield.setObjectName("searchfield")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(250, 70, 221, 31))
        self.comboBox.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setGeometry(QtCore.QRect(240, 160, 551, 441))
        self.tableWidget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.btn_refresh = QtWidgets.QPushButton(self.widget)
        self.btn_refresh.setGeometry(QtCore.QRect(650, 110, 141, 41))
        self.btn_refresh.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(251, 130, 255);\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-top :2px solid ;\n"
"border-left :2px solid ;\n"
"border-right :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"border-top-color: rgb(255, 170, 255);\n"
"border-right-color: rgb(255, 170, 255);\n"
"border-left-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ic/icons8-répéter-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_refresh.setIcon(icon5)
        self.btn_refresh.setIconSize(QtCore.QSize(50, 50))
        self.btn_refresh.setObjectName("btn_refresh")
        self.searchButton = QtWidgets.QPushButton(self.widget)
        self.searchButton.setGeometry(QtCore.QRect(490, 20, 91, 44))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.searchButton.setFont(font)
        self.searchButton.setStyleSheet("#searchButton\n"
"{\n"
"    text-align:left;\n"
"    padding-left:20px;\n"
"    border:none;\n"
"    border-left:6px solid dodgerblue;\n"
"    color:white;    \n"
"    background:#333333;\n"
"    background-color: rgb(27, 19, 57);\n"
"\n"
"}\n"
"#searchButton:hover\n"
"{\n"
"    text-align:left;\n"
"    padding-left:26px;\n"
"    border:none;    \n"
"    color:white;    \n"
"    background:#333;\n"
"    \n"
"}")
        self.searchButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ic/icons8-chercher-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon6)
        self.searchButton.setIconSize(QtCore.QSize(50, 50))
        self.searchButton.setObjectName("searchButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Gestion de stock</span></p></body></html>"))
        self.addEmpButton.setText(_translate("Form", "  Add Product"))
        self.updateEmpButton.setText(_translate("Form", "  Update Product"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;\">COPYRIGHT</span><span style=\" font-size:xx-large; font-weight:600; color:#ffffff;\">©</span></p></body></html>"))
        self.deletefield.setPlaceholderText(_translate("Form", "Product\'s id to delete"))
        self.nbrr.setText(_translate("Form", "Pourcentage des categories"))
        self.searchfield.setPlaceholderText(_translate("Form", "Search"))
        self.comboBox.setItemText(0, _translate("Form", "Prix unitaire"))
        self.comboBox.setItemText(1, _translate("Form", "Quantité"))
        self.comboBox.setItemText(2, _translate("Form", "Nom"))
        self.comboBox.setItemText(3, _translate("Form", "Date de dernière entrée en stock"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Id_produit"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Description"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Prix_unitaite"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Quantité"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "seuil_alerte_stock"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "date_derniere_entree"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "date_derniere_sortie"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "image"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Form", "id_categorie"))
        self.btn_refresh.setText(_translate("Form", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
