# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(578, 520)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 30, 550, 500))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(29, 29, 281, 431))
        self.label.setStyleSheet("border-image: url(:/IMAGES/GestionStock.png);\n"
"background-color: rgb(27, 19, 57);\n"
"border-bottom-left-radius:50px;\n"
"background-color: rgb(255, 255, 255);\n"
"background-color: rgb(27, 19, 57);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/image.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(310, 30, 211, 430))
        self.label_2.setStyleSheet("\n"
"border-bottom-right-radius:50px;\n"
"\n"
"background-color: rgb(27, 19, 57);\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(330, 80, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(181, 120, 255);\n"
"font: 28pt \"Snap ITC\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.usernamefield = QtWidgets.QLineEdit(self.widget)
        self.usernamefield.setGeometry(QtCore.QRect(339, 160, 171, 40))
        self.usernamefield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(251, 130, 255);\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"")
        self.usernamefield.setObjectName("usernamefield")
        self.passwordfield = QtWidgets.QLineEdit(self.widget)
        self.passwordfield.setGeometry(QtCore.QRect(339, 220, 171, 40))
        self.passwordfield.setStyleSheet("\n"
"background-color: rgb(27, 19, 57);\n"
"color: rgb(251, 130, 255);\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"")
        self.passwordfield.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordfield.setObjectName("passwordfield")
        self.login_btn = QtWidgets.QPushButton(self.widget)
        self.login_btn.setGeometry(QtCore.QRect(320, 290, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("QPushButton#login_btn{\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(181, 120, 255), stop:1 rgb(255, 170, 255));\n"
"\n"
"    color:rgba(255, 255, 255, 210);\n"
"\n"
"    border-radius:5px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton#login_btn:hover{\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(181, 120, 255), stop:1 rgb(255, 170, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#login_btn:pressed{\n"
"\n"
"    padding-left:5px;\n"
"\n"
"    padding-top:5px;\n"
"\n"
"    background-color:rgb(251, 130, 255);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#login_btn_2, #login_btn_3, #login_btn_4, #login_btn_5{\n"
"\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"\n"
"    color:rgb(251, 130, 255);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#login_btn_2:hover, #login_btn_3:hover, #login_btn_4:hover, #login_btn_5:hover{\n"
"\n"
"    color: rgb(251, 130, 255);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#login_btn_2:pressed, #login_btn_3:pressed, #login_btn_4:pressed, #login_btn_5:pressed{\n"
"\n"
"    padding-left:5px;\n"
"\n"
"    padding-top:5px;\n"
"\n"
"    color:rgb(251, 130, 255);;\n"
"\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ic/icons8-connexion-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_btn.setIcon(icon)
        self.login_btn.setIconSize(QtCore.QSize(40, 40))
        self.login_btn.setObjectName("login_btn")
        self.createacc_btn = QtWidgets.QPushButton(self.widget)
        self.createacc_btn.setGeometry(QtCore.QRect(320, 386, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        self.createacc_btn.setFont(font)
        self.createacc_btn.setStyleSheet("color: rgb(255, 170, 255);\n"
"background-color: rgb(27, 19, 57);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ic/icons8-ajouter-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createacc_btn.setIcon(icon1)
        self.createacc_btn.setIconSize(QtCore.QSize(40, 40))
        self.createacc_btn.setObjectName("createacc_btn")
        self.error = QtWidgets.QLabel(self.widget)
        self.error.setGeometry(QtCore.QRect(300, 340, 191, 21))
        self.error.setStyleSheet("color: rgb(255, 0, 0);")
        self.error.setText("")
        self.error.setObjectName("error")
        self.quitter = QtWidgets.QPushButton(self.widget)
        self.quitter.setGeometry(QtCore.QRect(490, 30, 31, 31))
        self.quitter.setStyleSheet("\n"
"\n"
"background-color: rgb(27, 19, 57);")
        self.quitter.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Web/icons8-annuler-stickers-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitter.setIcon(icon2)
        self.quitter.setIconSize(QtCore.QSize(96, 96))
        self.quitter.setObjectName("quitter")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(310, 220, 31, 41))
        self.pushButton.setStyleSheet("background-color: rgb(27, 19, 57);")
        self.pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ic/icons8-mot-de-passe-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 160, 31, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(27, 19, 57);")
        self.pushButton_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ic/icons8-utilisateur-masculin-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Log In"))
        self.usernamefield.setPlaceholderText(_translate("Form", "Username"))
        self.passwordfield.setPlaceholderText(_translate("Form", "Password"))
        self.login_btn.setText(_translate("Form", "LOGIN"))
        self.createacc_btn.setText(_translate("Form", "New? Create New Account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
