# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(801, 551)
        
        SplashScreen.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        SplashScreen.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShowdan = QtWidgets.QFrame(self.centralwidget)
        self.dropShowdan.setStyleSheet("QFrame {    \n"
"    background-color: rgb(27, 19, 57);\n"
"    \n"
"    \n"
"\n"
"    \n"
"\n"
"    color: rgb(181, 120, 255);\n"
"\n"
"    border-radius: 10px;\n"
"\n"
"}")
        self.dropShowdan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShowdan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShowdan.setObjectName("dropShowdan")
        self.progressBar = QtWidgets.QProgressBar(self.dropShowdan)
        self.progressBar.setGeometry(QtCore.QRect(9, 300, 761, 41))
        self.progressBar.setStyleSheet("QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));\n"
"}\n"
"\n"
"QProgressBar {\n"
"    background-color: rgb(82, 64, 157);\n"
"    color: #fff;\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    height: 50px;\n"
"}\n"
"\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.labelName = QtWidgets.QLabel(self.dropShowdan)
        self.labelName.setGeometry(QtCore.QRect(0, 120, 777, 66))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(48)
        self.labelName.setFont(font)
        self.labelName.setStyleSheet("QLabel{\n"
"    color: rgb(0, 85, 255);\n"
"    \n"
"    \n"
"}")
        self.labelName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelName.setObjectName("labelName")
        self.labelSubName = QtWidgets.QLabel(self.dropShowdan)
        self.labelSubName.setGeometry(QtCore.QRect(0, 200, 777, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.labelSubName.setFont(font)
        self.labelSubName.setStyleSheet("QLabel{\n"
"    color: rgb(255, 0, 255);\n"
"    \n"
"\n"
"height: 5px;\n"
"}")
        self.labelSubName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSubName.setObjectName("labelSubName")
        self.labelLoading = QtWidgets.QLabel(self.dropShowdan)
        self.labelLoading.setGeometry(QtCore.QRect(0, 370, 777, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.labelLoading.setFont(font)
        self.labelLoading.setStyleSheet("QLabel{\n"
" color: rgb(170, 170, 255);\n"
"height: 5px;\n"
"}")
        self.labelLoading.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLoading.setObjectName("labelLoading")
        self.labelCreated = QtWidgets.QLabel(self.dropShowdan)
        self.labelCreated.setGeometry(QtCore.QRect(0, 20, 761, 20))
        self.labelCreated.setStyleSheet("QLabel{\n"
" rgb(82, 64, 157)\n"
"height: 5px;\n"
"}")
        self.labelCreated.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCreated.setObjectName("labelCreated")
        self.verticalLayout.addWidget(self.dropShowdan)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.labelName.setText(_translate("SplashScreen", "<html><head/><body><p>Stock Management</p></body></html>"))
        self.labelSubName.setText(_translate("SplashScreen", "<html><head/><body><p>KASA</p><p><br/></p></body></html>"))
        self.labelLoading.setText(_translate("SplashScreen", "loading..."))
        self.labelCreated.setText(_translate("SplashScreen", "<html><head/><body><p>Emsi2023</p><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
