# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignUp_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(807, 604)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(40, 40, 741, 541))
        self.widget_2.setStyleSheet("\n"
"border-bottom-right-radius:50px;\n"
"border-top-left-radius:50px;\n"
"background-color: rgb(27, 19, 57);\n"
"\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(40, 20, 231, 571))
        self.label_4.setStyleSheet("\n"
"border-bottom-right-radius:50px;\n"
"border-top-left-radius:50px;\n"
"background-color: rgb(27, 19, 57);\n"
"\n"
"")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Images/GestionStock.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(70, 30, 521, 101))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(181, 120, 255);\n"
"font: 28pt \"Snap ITC\";\n"
"")
        self.label_6.setObjectName("label_6")
        self.usernamefield = QtWidgets.QLineEdit(self.widget_2)
        self.usernamefield.setGeometry(QtCore.QRect(430, 210, 251, 41))
        self.usernamefield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(255, 230, 250);\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"")
        self.usernamefield.setObjectName("usernamefield")
        self.passwordfield = QtWidgets.QLineEdit(self.widget_2)
        self.passwordfield.setGeometry(QtCore.QRect(70, 380, 251, 41))
        self.passwordfield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(255, 230, 250);\n"
"\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"")
        self.passwordfield.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordfield.setObjectName("passwordfield")
        self.btn_signup = QtWidgets.QPushButton(self.widget_2)
        self.btn_signup.setGeometry(QtCore.QRect(430, 380, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.btn_signup.setFont(font)
        self.btn_signup.setStyleSheet("QPushButton#btn_signup{\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(181, 120, 255), stop:1 rgb(255, 170, 255));\n"
"\n"
"    color:rgba(255, 255, 255, 210);\n"
"\n"
"    border-radius:5px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton#btn_signup:hover{\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(181, 120, 255), stop:1 rgb(255, 170, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#lbtn_signup:pressed{\n"
"\n"
"    padding-left:5px;\n"
"\n"
"    padding-top:5px;\n"
"\n"
"    background-color:rgb(251, 130, 255);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#btn_signup_2, #btn_signup_3, #btn_signup_4, #btn_signup_5{\n"
"\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"\n"
"    color:rgb(251, 130, 255);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#login_btn_2:hover, #login_btn_3:hover, #login_btn_4:hover, #login_btn_5:hover{\n"
"\n"
"    color: rgb(251, 130, 255);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#login_btn_2:pressed, #login_btn_3:pressed, #login_btn_4:pressed, #login_btn_5:pressed{\n"
"\n"
"    padding-left:5px;\n"
"\n"
"    padding-top:5px;\n"
"\n"
"    color:rgb(251, 130, 255);;\n"
"\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ic/icons8-ajouter-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_signup.setIcon(icon)
        self.btn_signup.setIconSize(QtCore.QSize(40, 40))
        self.btn_signup.setObjectName("btn_signup")
        self.emailfield = QtWidgets.QLineEdit(self.widget_2)
        self.emailfield.setGeometry(QtCore.QRect(70, 300, 251, 41))
        self.emailfield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(255, 230, 250);\n"
"\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"")
        self.emailfield.setObjectName("emailfield")
        self.C_passwordfield = QtWidgets.QLineEdit(self.widget_2)
        self.C_passwordfield.setGeometry(QtCore.QRect(70, 440, 251, 41))
        self.C_passwordfield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(255, 230, 250);\n"
"\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"")
        self.C_passwordfield.setEchoMode(QtWidgets.QLineEdit.Password)
        self.C_passwordfield.setObjectName("C_passwordfield")
        self.telephonefield = QtWidgets.QLineEdit(self.widget_2)
        self.telephonefield.setGeometry(QtCore.QRect(420, 300, 271, 41))
        self.telephonefield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(255, 230, 250);\n"
"\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"")
        self.telephonefield.setObjectName("telephonefield")
        self.first_namefield = QtWidgets.QLineEdit(self.widget_2)
        self.first_namefield.setGeometry(QtCore.QRect(70, 160, 251, 41))
        self.first_namefield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(255, 230, 250);\n"
"\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"\n"
"")
        self.first_namefield.setText("")
        self.first_namefield.setCursorPosition(0)
        self.first_namefield.setObjectName("first_namefield")
        self.last_namefield = QtWidgets.QLineEdit(self.widget_2)
        self.last_namefield.setGeometry(QtCore.QRect(70, 230, 251, 41))
        self.last_namefield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(255, 230, 250);\n"
"\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"")
        self.last_namefield.setText("")
        self.last_namefield.setCursorPosition(0)
        self.last_namefield.setObjectName("last_namefield")
        self.error5 = QtWidgets.QLabel(self.widget_2)
        self.error5.setGeometry(QtCore.QRect(40, 420, 301, 16))
        self.error5.setStyleSheet("color: rgb(170, 0, 0);")
        self.error5.setText("")
        self.error5.setObjectName("error5")
        self.error4 = QtWidgets.QLabel(self.widget_2)
        self.error4.setGeometry(QtCore.QRect(40, 340, 301, 16))
        self.error4.setStyleSheet("color: rgb(170, 0, 0);")
        self.error4.setText("")
        self.error4.setObjectName("error4")
        self.error3 = QtWidgets.QLabel(self.widget_2)
        self.error3.setGeometry(QtCore.QRect(40, 280, 301, 16))
        self.error3.setStyleSheet("color: rgb(170, 0, 0);")
        self.error3.setText("")
        self.error3.setObjectName("error3")
        self.error2 = QtWidgets.QLabel(self.widget_2)
        self.error2.setGeometry(QtCore.QRect(40, 210, 301, 16))
        self.error2.setStyleSheet("color: rgb(170, 0, 0);")
        self.error2.setText("")
        self.error2.setObjectName("error2")
        self.error1 = QtWidgets.QLabel(self.widget_2)
        self.error1.setGeometry(QtCore.QRect(400, 270, 301, 16))
        self.error1.setStyleSheet("color: rgb(170, 0, 0);")
        self.error1.setText("")
        self.error1.setObjectName("error1")
        self.error7 = QtWidgets.QLabel(self.widget_2)
        self.error7.setGeometry(QtCore.QRect(370, 350, 301, 16))
        self.error7.setStyleSheet("color: rgb(170, 0, 0);")
        self.error7.setText("")
        self.error7.setObjectName("error7")
        self.error9 = QtWidgets.QLabel(self.widget_2)
        self.error9.setGeometry(QtCore.QRect(380, 460, 301, 16))
        self.error9.setStyleSheet("color: rgb(170, 0, 0);")
        self.error9.setText("")
        self.error9.setObjectName("error9")
        self.error6 = QtWidgets.QLabel(self.widget_2)
        self.error6.setGeometry(QtCore.QRect(40, 490, 301, 16))
        self.error6.setStyleSheet("color: rgb(170, 0, 0);")
        self.error6.setText("")
        self.error6.setObjectName("error6")
        self.error = QtWidgets.QLabel(self.widget_2)
        self.error.setGeometry(QtCore.QRect(380, 500, 311, 16))
        self.error.setStyleSheet("color: rgb(170, 0, 0);")
        self.error.setText("")
        self.error.setObjectName("error")
        self.error41 = QtWidgets.QLabel(self.widget_2)
        self.error41.setGeometry(QtCore.QRect(40, 360, 301, 16))
        self.error41.setStyleSheet("color: rgb(170, 0, 0);")
        self.error41.setText("")
        self.error41.setObjectName("error41")
        self.error71 = QtWidgets.QLabel(self.widget_2)
        self.error71.setGeometry(QtCore.QRect(390, 160, 301, 16))
        self.error71.setStyleSheet("color: rgb(170, 0, 0);")
        self.error71.setText("")
        self.error71.setObjectName("error71")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 210, 61, 41))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ic/icons8-nom-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 160, 51, 41))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ic/icons8-utilisateur-masculin-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 300, 61, 41))
        self.pushButton_5.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ic/icons8-email-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 380, 51, 41))
        self.pushButton_6.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ic/icons8-mot-de-passe-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 443, 51, 41))
        self.pushButton_7.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ic/icons8-mot-de-passe-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon5)
        self.pushButton_7.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_8.setGeometry(QtCore.QRect(350, 310, 61, 31))
        self.pushButton_8.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ic/icons8-téléphone-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon6)
        self.pushButton_8.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 230, 51, 41))
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_9.setGeometry(QtCore.QRect(670, 0, 75, 61))
        self.pushButton_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_9.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ic/icons8-sortie-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon7)
        self.pushButton_9.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_9.setObjectName("pushButton_9")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Sign UP \n"
" Fill in the form"))
        self.usernamefield.setPlaceholderText(_translate("Form", "Username"))
        self.passwordfield.setPlaceholderText(_translate("Form", "Password "))
        self.btn_signup.setText(_translate("Form", "Sign up"))
        self.emailfield.setPlaceholderText(_translate("Form", "Email"))
        self.C_passwordfield.setPlaceholderText(_translate("Form", "Confirm Password"))
        self.telephonefield.setPlaceholderText(_translate("Form", "Téléphone"))
        self.first_namefield.setPlaceholderText(_translate("Form", "First name"))
        self.last_namefield.setPlaceholderText(_translate("Form", "Last name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
