# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'upload.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        Form.resize(852, 691)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(10, 0, 791, 611))
        self.widget_2.setStyleSheet("\n"
"border-bottom-right-radius:50px;\n"
"border-top-left-radius:50px;\n"
"background-color: rgb(27, 19, 57);\n"
"\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(40, 20, 231, 571))
        self.label_4.setStyleSheet("\n"
"border-bottom-right-radius:50px;\n"
"border-top-left-radius:50px;\n"
"background-color: rgb(27, 19, 57);\n"
"\n"
"")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Images/GestionStock.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(200, 10, 491, 51))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(181, 120, 255);\n"
"font: 28pt \"Snap ITC\";\n"
"")
        self.label_6.setObjectName("label_6")
        self.namefield = QtWidgets.QLineEdit(self.widget_2)
        self.namefield.setGeometry(QtCore.QRect(100, 130, 191, 41))
        self.namefield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(255, 230, 250);\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"")
        self.namefield.setObjectName("namefield")
        self.btn_add1 = QtWidgets.QPushButton(self.widget_2)
        self.btn_add1.setGeometry(QtCore.QRect(600, 190, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.btn_add1.setFont(font)
        self.btn_add1.setStyleSheet("QPushButton#btn_add1{\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(181, 120, 255), stop:1 rgb(255, 170, 255));\n"
"\n"
"    color:rgba(255, 255, 255, 210);\n"
"\n"
"    border-radius:5px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton#btn_add1:hover{\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(181, 120, 255), stop:1 rgb(255, 170, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#btn_add1:pressed{\n"
"\n"
"    padding-left:5px;\n"
"\n"
"    padding-top:5px;\n"
"\n"
"    background-color:rgb(251, 130, 255);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#btn_add1, #btn_add1, #btn_add1, #btn_add1{\n"
"\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"\n"
"    color:rgb(251, 130, 255);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#btn_add1:hover, #btn_add1:hover, #btn_add1:hover, #btn_add1:hover{\n"
"\n"
"    color: rgb(251, 130, 255);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#btn_add1:pressed, #btn_add1:pressed, #btn_add1:pressed, #btn_add1:pressed{\n"
"\n"
"    padding-left:5px;\n"
"\n"
"    padding-top:5px;\n"
"\n"
"    color:rgb(251, 130, 255);;\n"
"\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ic/UPDATE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add1.setIcon(icon)
        self.btn_add1.setIconSize(QtCore.QSize(50, 50))
        self.btn_add1.setObjectName("btn_add1")
        self.seuilfield = QtWidgets.QLineEdit(self.widget_2)
        self.seuilfield.setGeometry(QtCore.QRect(390, 210, 191, 41))
        self.seuilfield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(255, 230, 250);\n"
"\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"")
        self.seuilfield.setObjectName("seuilfield")
        self.descfield = QtWidgets.QLineEdit(self.widget_2)
        self.descfield.setGeometry(QtCore.QRect(100, 210, 191, 41))
        self.descfield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(255, 230, 250);\n"
"\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"\n"
"")
        self.descfield.setText("")
        self.descfield.setCursorPosition(0)
        self.descfield.setObjectName("descfield")
        self.prixfield = QtWidgets.QLineEdit(self.widget_2)
        self.prixfield.setGeometry(QtCore.QRect(390, 130, 191, 41))
        self.prixfield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(255, 230, 250);\n"
"\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"")
        self.prixfield.setText("")
        self.prixfield.setCursorPosition(0)
        self.prixfield.setObjectName("prixfield")
        self.error5 = QtWidgets.QLabel(self.widget_2)
        self.error5.setGeometry(QtCore.QRect(40, 350, 301, 16))
        self.error5.setStyleSheet("color: rgb(170, 0, 0);")
        self.error5.setText("")
        self.error5.setObjectName("error5")
        self.error4 = QtWidgets.QLabel(self.widget_2)
        self.error4.setGeometry(QtCore.QRect(360, 260, 301, 16))
        self.error4.setStyleSheet("color: rgb(170, 0, 0);")
        self.error4.setText("")
        self.error4.setObjectName("error4")
        self.error3 = QtWidgets.QLabel(self.widget_2)
        self.error3.setGeometry(QtCore.QRect(360, 180, 301, 16))
        self.error3.setStyleSheet("color: rgb(170, 0, 0);")
        self.error3.setText("")
        self.error3.setObjectName("error3")
        self.error2 = QtWidgets.QLabel(self.widget_2)
        self.error2.setGeometry(QtCore.QRect(40, 260, 301, 16))
        self.error2.setStyleSheet("color: rgb(170, 0, 0);")
        self.error2.setText("")
        self.error2.setObjectName("error2")
        self.error1 = QtWidgets.QLabel(self.widget_2)
        self.error1.setGeometry(QtCore.QRect(40, 180, 281, 16))
        self.error1.setStyleSheet("color: rgb(170, 0, 0);")
        self.error1.setText("")
        self.error1.setObjectName("error1")
        self.error = QtWidgets.QLabel(self.widget_2)
        self.error.setGeometry(QtCore.QRect(150, 120, 341, 16))
        self.error.setStyleSheet("color: rgb(170, 0, 0);")
        self.error.setText("")
        self.error.setObjectName("error")
        self.quantitefield = QtWidgets.QLineEdit(self.widget_2)
        self.quantitefield.setGeometry(QtCore.QRect(100, 300, 191, 41))
        self.quantitefield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(255, 230, 250);\n"
"\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"")
        self.quantitefield.setText("")
        self.quantitefield.setCursorPosition(0)
        self.quantitefield.setObjectName("quantitefield")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 130, 75, 41))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ic/icons8-badge-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 210, 75, 41))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ic/icons8-télécharger-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 130, 75, 41))
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ic/icons8-étiquette-de-prix-usd-40.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 220, 75, 41))
        self.pushButton_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ic/icons8-produit-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 300, 75, 41))
        self.pushButton_6.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ic/icons8-vendre-les-stock-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.idfield = QtWidgets.QLineEdit(self.widget_2)
        self.idfield.setGeometry(QtCore.QRect(150, 70, 321, 41))
        self.idfield.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(255, 230, 250);\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"\n"
"\n"
"")
        self.idfield.setObjectName("idfield")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 380, 631, 201))
        self.tableWidget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.btn_refresh = QtWidgets.QPushButton(self.widget_2)
        self.btn_refresh.setGeometry(QtCore.QRect(650, 470, 131, 41))
        self.btn_refresh.setStyleSheet("background-color: rgb(27, 19, 57);\n"
"color: rgb(251, 130, 255);\n"
"\n"
"\n"
"border:none;\n"
"border-bottom :2px solid ;\n"
"border-top :2px solid ;\n"
"border-left :2px solid ;\n"
"border-right :2px solid ;\n"
"border-bottom-color: rgb(255, 170, 255);\n"
"border-top-color: rgb(255, 170, 255);\n"
"border-right-color: rgb(255, 170, 255);\n"
"border-left-color: rgb(255, 170, 255);\n"
"padding-bottom:7px;\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ic/icons8-répéter-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_refresh.setIcon(icon6)
        self.btn_refresh.setIconSize(QtCore.QSize(50, 50))
        self.btn_refresh.setObjectName("btn_refresh")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_7.setGeometry(QtCore.QRect(710, 0, 75, 61))
        self.pushButton_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_7.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ic/icons8-sortie-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon7)
        self.pushButton_7.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_7.setObjectName("pushButton_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "UPDATE PRODUCT"))
        self.namefield.setPlaceholderText(_translate("Form", "Name"))
        self.btn_add1.setText(_translate("Form", "UPDATE"))
        self.seuilfield.setPlaceholderText(_translate("Form", "seuil alerte de stock"))
        self.descfield.setPlaceholderText(_translate("Form", "Description"))
        self.prixfield.setPlaceholderText(_translate("Form", "Prix Unitaire"))
        self.quantitefield.setPlaceholderText(_translate("Form", "quantite"))
        self.idfield.setPlaceholderText(_translate("Form", "Id Product"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Id_produit"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Description"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Prix_unitaite"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Quantité"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "seuil_alerte_stock"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "date_derniere_entree"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "date_derniere_sortie"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "image"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Form", "id_categorie"))
        self.btn_refresh.setText(_translate("Form", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
